### ISSUE TITLE
Build a nextJS 13 app

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/decenterai.com#18]
Follow this tutorial and build the movie app:

https://www.youtube.com/watch?v=T63nY70eZF0

**Comment by Dineshjnld** [comment]
![Image](https://github.com/DeCenter-AI/decenterai.com/assets/106725225/5de48721-6c5b-46a0-bf20-371a50bcb7f2)



![Image](https://github.com/DeCenter-AI/decenterai.com/assets/106725225/7552898e-b806-49fa-a185-5d6c2ed3ec9f)



![Image](https://github.com/DeCenter-AI/decenterai.com/assets/106725225/0ea51223-3f27-45f1-a9b2-d9b5820d90f9)



![Image](https://github.com/DeCenter-AI/decenterai.com/assets/106725225/6e70dfaa-29ce-4084-a1eb-b3eabddce0b8)

**Comment by Dineshjnld** [comment]
**repo link:**
https://github.com/Dineshjnld/nextjs-issue-tracker
