### ISSUE TITLE
chore: migrate favicons from app.decenterai.com

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/decenterai.com#46]
- [ ] take meta configuration from https://github.com/DeCenter-AI/app.decenterai.com/blob/main/src/app/layout.tsx#L17
- [ ] also copy the favicons, and related files from public folder
- [ ] check the favicons with vercel preview deployment url over here: https://realfavicongenerator.net/favicon_checker

Reference: https://realfavicongenerator.net/favicon_checker?protocol=http&site=app.decenterai.com

**Comment by utkarsh-1602** [comment]
https://e861-2401-4900-1c44-1bcd-7fb3-4a91-b1a-1231.ngrok-free.app/ 
@Nasfame I've imported the meta configuration and and favicons, but its still giving errors at favicons checker

**Comment by Nasfame** [comment]
oh, ok @utkarsh-1602 assign the pr to me, i ill take a look

**Comment by utkarsh-1602** [comment]
yes, I've assigned https://github.com/DeCenter-AI/decenterai.com/pull/47
